### ISSUE TITLE
[v3] Use demo as visual test

### ISSUE THREAD

**Issue by gakimball** [zurb/joyride#206]
Looking at the codebase, we have `demo/` folder, which is good for testing the interactions and visuals of the plugin and so on. There's also a visual test folder, which appears to have leftover files from the Foundation 6 visual test suite.

What if the contents of `demo/` become the visual tests? So you have the automated unit tests through Mocha, and then the visual tests for directly interacting with the plugin.

**Comment by Owlbertz** [comment]
Done with https://github.com/zurb/joyride/commit/f3d23ea167f3011522c1f278947ba34843b1904d.
