### ISSUE TITLE
[v3] npm commands

### ISSUE THREAD

**Issue by gakimball** [zurb/joyride#207]
Whatever structure we come up with here will be used as a standard for any future standalone Foundation plugins, so let's figure out what the commands are. My suggestions:

- `npm test`: Runs `npm run test:javascript`. Used by Travis for headless testing.
- `npm run test:javascript`: Runs Mocha in PhantomJS.
- `npm run test:visual`: Runs visual regression tests/live demos.
- `npm run dist`: Produces dist files for new versions.

**Comment by Owlbertz** [comment]
Currently the build process with running `gulp` will result in new files in the dist folder. Would you like to have these in the build folder during normal building, and only get moved into dist when running `npm run dist`?

**Comment by gakimball** [comment]
That would be better. The convention we use in the other repos is `_build` for the temporary build folder.

`dist` is just JS and CSS assets, in compressed and uncompressed flavors. And for this codebase, standalone and dependent versions.

**Comment by Owlbertz** [comment]
Ok, I will adjust the build tasks accors indingly so they will not directly create the files in the dist folder, but within the build folder.
Files in the dist folder will then only be created when the corresponding `gulp dist` or `npm run dist` are used.

**Comment by Owlbertz** [comment]
Done in https://github.com/zurb/joyride/commit/04124b055bc269eb265bb0817af0c144c3fea367.
