### ISSUE TITLE
[v3] Setup doesn't work with npm 3

### ISSUE THREAD

**Issue by gakimball** [zurb/joyride#211]
The paths to jQuery in the demo, tests, etc. are written as:

`node_modules/foundation-sites/node_modules/jquery/dist/jquery.js`

If you're using npm 3, which installs all dependencies flat, the path is different:

`node_modules/jquery/dist/jquery.js`

So the tests fail and the demo page doesn't initialize properly.

To make the path more predictable, add `jquery` as a devDependency. Then in npm 2 and 3, the jQuery folder will always be in the same place.

**Comment by Owlbertz** [comment]
Done in https://github.com/zurb/joyride/commit/19bb4f9d079260169eef83ea2003730b376f1f9a.
