### ISSUE TITLE
[v3] Reduce boilerplate in JavaScript test folder

### ISSUE THREAD

**Issue by gakimball** [zurb/joyride#212]
Under `test/javascript`, there's only one test in the `components/` folder, so that could be moved to sit next to `index.html`, and the `components/` folder removed. The standalone plugins will all likely have just one test file, so putting it in a folder isn't necessary.

Also, if you aren't using Sinon, you can remove it from the `lib/` folder. Makes the whole thing more slim. :)

**Comment by Owlbertz** [comment]
Done in https://github.com/zurb/joyride/commit/a12c16ab2b7ff15992dbff0f4a7f3aae55473b00, https://github.com/zurb/joyride/commit/19bb4f9d079260169eef83ea2003730b376f1f9a and https://github.com/zurb/joyride/commit/1161be94c968078e4b3d9a3030556677e67f87bd.
