### ISSUE TITLE
My joyride is placed wrong...

### ISSUE THREAD

**Issue by krillehbg** [zurb/joyride#80]
![image](https://f.cloud.github.com/assets/3806770/235916/ce1c6d74-87cc-11e2-81a8-bce4aa03c85e.png)

form id="form1" runat="server">
         <div id="helper10" style="width:200px; height:50px;background-color:Green;">
            TESTAR LITE
        </div>

         
         <ol id="joyRideTipContent">
          <li data-id="helper10" data-button="Nästa">
            <h2>Stop #5</h2>
            <p>It works as a modal too!</p>
          </li>
        </ol>

        
    <script type="text/javascript">
        $(window).load(function () {
            $('#joyRideTipContent').joyride({ postStepCallback: function (index, tip) {
                if (index == 2) {
                    $(this).joyride('set_li', false, 1);
                }
            },
                modal: true,
                expose: true
            });
        });
    </script>

    </form>

**Comment by pheelee** [comment]
don't know if you guys already found a solution.
this worked for me, either in a css or in the html file:

    <style>
    body{
    margin:0px;
    }
    </style
